export interface RealHighSchoolSeed {
  schoolName: string;
  city: string;
  state: string;
  mascot: string;
}

export const realHighSchoolSeeds: RealHighSchoolSeed[] = [
  { schoolName: 'Allen High School', city: 'Allen', state: 'TX', mascot: 'Eagles' },
  { schoolName: 'Duncanville High School', city: 'Duncanville', state: 'TX', mascot: 'Panthers' },
  { schoolName: 'DeSoto High School', city: 'DeSoto', state: 'TX', mascot: 'Eagles' },
  { schoolName: 'North Shore Senior High School', city: 'Houston', state: 'TX', mascot: 'Mustangs' },
  { schoolName: 'Southlake Carroll High School', city: 'Southlake', state: 'TX', mascot: 'Dragons' },
  { schoolName: 'Katy High School', city: 'Katy', state: 'TX', mascot: 'Tigers' },
  { schoolName: 'Westlake High School', city: 'Austin', state: 'TX', mascot: 'Chaparrals' },
  { schoolName: 'Lake Travis High School', city: 'Austin', state: 'TX', mascot: 'Cavaliers' },
  { schoolName: 'Aledo High School', city: 'Aledo', state: 'TX', mascot: 'Bearcats' },
  { schoolName: 'Denton Guyer High School', city: 'Denton', state: 'TX', mascot: 'Wildcats' },
  { schoolName: 'Cedar Hill High School', city: 'Cedar Hill', state: 'TX', mascot: 'Longhorns' },
  { schoolName: 'Longview High School', city: 'Longview', state: 'TX', mascot: 'Lobos' },
  { schoolName: 'Highland Park High School', city: 'Dallas', state: 'TX', mascot: 'Scots' },
  { schoolName: 'Rockwall-Heath High School', city: 'Rockwall', state: 'TX', mascot: 'Hawks' },
  { schoolName: 'Permian High School', city: 'Odessa', state: 'TX', mascot: 'Panthers' },
  { schoolName: 'Midland Legacy High School', city: 'Midland', state: 'TX', mascot: 'Rebels' },
  { schoolName: 'Trinity High School', city: 'Euless', state: 'TX', mascot: 'Trojans' },
  { schoolName: 'Atascocita High School', city: 'Humble', state: 'TX', mascot: 'Eagles' },
  { schoolName: 'Shadow Creek High School', city: 'Pearland', state: 'TX', mascot: 'Sharks' },
  { schoolName: 'Manvel High School', city: 'Manvel', state: 'TX', mascot: 'Mavericks' },
  { schoolName: 'Carthage High School', city: 'Carthage', state: 'TX', mascot: 'Bulldogs' },
  { schoolName: 'Argyle High School', city: 'Argyle', state: 'TX', mascot: 'Eagles' },
  { schoolName: 'Ryan High School', city: 'Denton', state: 'TX', mascot: 'Raiders' },
  { schoolName: 'Vandegrift High School', city: 'Austin', state: 'TX', mascot: 'Vipers' },
  { schoolName: 'Mater Dei High School', city: 'Santa Ana', state: 'CA', mascot: 'Monarchs' },
  { schoolName: 'St. John Bosco High School', city: 'Bellflower', state: 'CA', mascot: 'Braves' },
  { schoolName: 'Centennial High School', city: 'Corona', state: 'CA', mascot: 'Huskies' },
  { schoolName: 'Mission Viejo High School', city: 'Mission Viejo', state: 'CA', mascot: 'Diablos' },
  { schoolName: 'De La Salle High School', city: 'Concord', state: 'CA', mascot: 'Spartans' },
  { schoolName: 'Folsom High School', city: 'Folsom', state: 'CA', mascot: 'Bulldogs' },
  { schoolName: 'Sierra Canyon School', city: 'Chatsworth', state: 'CA', mascot: 'Trailblazers' },
  { schoolName: 'Los Alamitos High School', city: 'Los Alamitos', state: 'CA', mascot: 'Griffins' },
  { schoolName: 'Long Beach Polytechnic High School', city: 'Long Beach', state: 'CA', mascot: 'Jackrabbits' },
  { schoolName: 'Servite High School', city: 'Anaheim', state: 'CA', mascot: 'Friars' },
  { schoolName: 'Orange Lutheran High School', city: 'Orange', state: 'CA', mascot: 'Lancers' },
  { schoolName: 'JSerra Catholic High School', city: 'San Juan Capistrano', state: 'CA', mascot: 'Lions' },
  { schoolName: 'Bishop Amat High School', city: 'La Puente', state: 'CA', mascot: 'Lancers' },
  { schoolName: 'Serra High School', city: 'Gardena', state: 'CA', mascot: 'Cavaliers' },
  { schoolName: 'Santa Margarita Catholic High School', city: 'Rancho Santa Margarita', state: 'CA', mascot: 'Eagles' },
  { schoolName: 'San Clemente High School', city: 'San Clemente', state: 'CA', mascot: 'Tritons' },
  { schoolName: 'Edison High School', city: 'Huntington Beach', state: 'CA', mascot: 'Chargers' },
  { schoolName: 'Oaks Christian School', city: 'Westlake Village', state: 'CA', mascot: 'Lions' },
  { schoolName: 'IMG Academy', city: 'Bradenton', state: 'FL', mascot: 'Ascenders' },
  { schoolName: 'St. Thomas Aquinas High School', city: 'Fort Lauderdale', state: 'FL', mascot: 'Raiders' },
  { schoolName: 'Chaminade-Madonna College Preparatory', city: 'Hollywood', state: 'FL', mascot: 'Lions' },
  { schoolName: 'Miami Central High School', city: 'Miami', state: 'FL', mascot: 'Rockets' },
  { schoolName: 'Miami Northwestern Senior High School', city: 'Miami', state: 'FL', mascot: 'Bulls' },
  { schoolName: 'American Heritage School', city: 'Plantation', state: 'FL', mascot: 'Patriots' },
  { schoolName: 'Cardinal Gibbons High School', city: 'Fort Lauderdale', state: 'FL', mascot: 'Chiefs' },
  { schoolName: 'Venice High School', city: 'Venice', state: 'FL', mascot: 'Indians' },
  { schoolName: 'Lakeland High School', city: 'Lakeland', state: 'FL', mascot: 'Dreadnaughts' },
  { schoolName: 'Armwood High School', city: 'Seffner', state: 'FL', mascot: 'Hawks' },
  { schoolName: 'Buchholz High School', city: 'Gainesville', state: 'FL', mascot: 'Bobcats' },
  { schoolName: 'Cocoa High School', city: 'Cocoa', state: 'FL', mascot: 'Tigers' },
  { schoolName: 'Edgewater High School', city: 'Orlando', state: 'FL', mascot: 'Eagles' },
  { schoolName: 'Jones High School', city: 'Orlando', state: 'FL', mascot: 'Tigers' },
  { schoolName: 'Apopka High School', city: 'Apopka', state: 'FL', mascot: 'Blue Darters' },
  { schoolName: 'Seminole High School', city: 'Sanford', state: 'FL', mascot: 'Seminoles' },
  { schoolName: 'Trinity Christian Academy', city: 'Jacksonville', state: 'FL', mascot: 'Conquerors' },
  { schoolName: 'Naples High School', city: 'Naples', state: 'FL', mascot: 'Golden Eagles' },
  { schoolName: 'Buford High School', city: 'Buford', state: 'GA', mascot: 'Wolves' },
  { schoolName: 'Mill Creek High School', city: 'Hoschton', state: 'GA', mascot: 'Hawks' },
  { schoolName: 'Colquitt County High School', city: 'Moultrie', state: 'GA', mascot: 'Packers' },
  { schoolName: 'Grayson High School', city: 'Loganville', state: 'GA', mascot: 'Rams' },
  { schoolName: 'Carrollton High School', city: 'Carrollton', state: 'GA', mascot: 'Trojans' },
  { schoolName: 'North Gwinnett High School', city: 'Suwanee', state: 'GA', mascot: 'Bulldogs' },
  { schoolName: 'Valdosta High School', city: 'Valdosta', state: 'GA', mascot: 'Wildcats' },
  { schoolName: 'Lee County High School', city: 'Leesburg', state: 'GA', mascot: 'Trojans' },
  { schoolName: 'Lowndes High School', city: 'Valdosta', state: 'GA', mascot: 'Vikings' },
  { schoolName: 'Milton High School', city: 'Milton', state: 'GA', mascot: 'Eagles' },
  { schoolName: 'Walton High School', city: 'Marietta', state: 'GA', mascot: 'Raiders' },
  { schoolName: 'Warner Robins High School', city: 'Warner Robins', state: 'GA', mascot: 'Demons' },
  { schoolName: 'Cedar Grove High School', city: 'Ellenwood', state: 'GA', mascot: 'Saints' },
  { schoolName: 'Rome High School', city: 'Rome', state: 'GA', mascot: 'Wolves' },
  { schoolName: 'Langston Hughes High School', city: 'Fairburn', state: 'GA', mascot: 'Panthers' },
  { schoolName: 'St. Edward High School', city: 'Lakewood', state: 'OH', mascot: 'Eagles' },
  { schoolName: 'St. Ignatius High School', city: 'Cleveland', state: 'OH', mascot: 'Wildcats' },
  { schoolName: 'Archbishop Hoban High School', city: 'Akron', state: 'OH', mascot: 'Knights' },
  { schoolName: 'Washington High School', city: 'Massillon', state: 'OH', mascot: 'Tigers' },
  { schoolName: 'Moeller High School', city: 'Cincinnati', state: 'OH', mascot: 'Crusaders' },
  { schoolName: 'Elder High School', city: 'Cincinnati', state: 'OH', mascot: 'Panthers' },
  { schoolName: 'Lakota West High School', city: 'West Chester', state: 'OH', mascot: 'Firebirds' },
  { schoolName: 'Pickerington Central High School', city: 'Pickerington', state: 'OH', mascot: 'Tigers' },
  { schoolName: 'Avon High School', city: 'Avon', state: 'OH', mascot: 'Eagles' },
  { schoolName: 'Springfield High School', city: 'Springfield', state: 'OH', mascot: 'Wildcats' },
  { schoolName: 'Mentor High School', city: 'Mentor', state: 'OH', mascot: 'Cardinals' },
  { schoolName: 'Winton Woods High School', city: 'Cincinnati', state: 'OH', mascot: 'Warriors' },
  { schoolName: "St. Joseph's Preparatory School", city: 'Philadelphia', state: 'PA', mascot: 'Hawks' },
  { schoolName: 'Central Catholic High School', city: 'Pittsburgh', state: 'PA', mascot: 'Vikings' },
  { schoolName: 'Pine-Richland High School', city: 'Gibsonia', state: 'PA', mascot: 'Rams' },
  { schoolName: 'Imhotep Institute Charter High School', city: 'Philadelphia', state: 'PA', mascot: 'Panthers' },
  { schoolName: 'Harrisburg High School', city: 'Harrisburg', state: 'PA', mascot: 'Cougars' },
  { schoolName: 'North Allegheny High School', city: 'Wexford', state: 'PA', mascot: 'Tigers' },
  { schoolName: 'Malvern Preparatory School', city: 'Malvern', state: 'PA', mascot: 'Friars' },
  { schoolName: 'La Salle College High School', city: 'Wyndmoor', state: 'PA', mascot: 'Explorers' },
  { schoolName: 'Bergen Catholic High School', city: 'Oradell', state: 'NJ', mascot: 'Crusaders' },
  { schoolName: 'Don Bosco Preparatory High School', city: 'Ramsey', state: 'NJ', mascot: 'Ironmen' },
  { schoolName: "St. Peter's Preparatory School", city: 'Jersey City', state: 'NJ', mascot: 'Marauders' },
  { schoolName: 'DePaul Catholic High School', city: 'Wayne', state: 'NJ', mascot: 'Spartans' },
  { schoolName: 'Paramus Catholic High School', city: 'Paramus', state: 'NJ', mascot: 'Paladins' },
  { schoolName: 'Good Counsel High School', city: 'Olney', state: 'MD', mascot: 'Falcons' },
  { schoolName: 'DeMatha Catholic High School', city: 'Hyattsville', state: 'MD', mascot: 'Stags' },
  { schoolName: 'St. Frances Academy', city: 'Baltimore', state: 'MD', mascot: 'Panthers' },
  { schoolName: "St. John's College High School", city: 'Washington', state: 'DC', mascot: 'Cadets' },
  { schoolName: 'Gonzaga College High School', city: 'Washington', state: 'DC', mascot: 'Eagles' },
  { schoolName: 'Stone Bridge High School', city: 'Ashburn', state: 'VA', mascot: 'Bulldogs' },
  { schoolName: 'Highland Springs High School', city: 'Highland Springs', state: 'VA', mascot: 'Springers' },
  { schoolName: 'Oscar Smith High School', city: 'Chesapeake', state: 'VA', mascot: 'Tigers' },
  { schoolName: 'Phoebus High School', city: 'Hampton', state: 'VA', mascot: 'Phantoms' },
  { schoolName: 'Dutch Fork High School', city: 'Irmo', state: 'SC', mascot: 'Silver Foxes' },
  { schoolName: 'Gaffney High School', city: 'Gaffney', state: 'SC', mascot: 'Indians' },
  { schoolName: 'Byrnes High School', city: 'Duncan', state: 'SC', mascot: 'Rebels' },
  { schoolName: 'Northwestern High School', city: 'Rock Hill', state: 'SC', mascot: 'Trojans' },
  { schoolName: 'Chambers High School', city: 'Charlotte', state: 'NC', mascot: 'Cougars' },
  { schoolName: 'Mallard Creek High School', city: 'Charlotte', state: 'NC', mascot: 'Mavericks' },
  { schoolName: 'Grimsley High School', city: 'Greensboro', state: 'NC', mascot: 'Whirlies' },
  { schoolName: 'Rolesville High School', city: 'Rolesville', state: 'NC', mascot: 'Rams' },
  { schoolName: 'Oak Grove High School', city: 'Hattiesburg', state: 'MS', mascot: 'Warriors' },
  { schoolName: 'Brandon High School', city: 'Brandon', state: 'MS', mascot: 'Bulldogs' },
  { schoolName: 'Madison Central High School', city: 'Madison', state: 'MS', mascot: 'Jaguars' },
  { schoolName: 'South Panola High School', city: 'Batesville', state: 'MS', mascot: 'Tigers' },
  { schoolName: 'Hoover High School', city: 'Hoover', state: 'AL', mascot: 'Buccaneers' },
  { schoolName: 'Thompson High School', city: 'Alabaster', state: 'AL', mascot: 'Warriors' },
  { schoolName: 'Central High School', city: 'Phenix City', state: 'AL', mascot: 'Red Devils' },
  { schoolName: 'Auburn High School', city: 'Auburn', state: 'AL', mascot: 'Tigers' },
  { schoolName: 'Lipscomb Academy', city: 'Nashville', state: 'TN', mascot: 'Mustangs' },
  { schoolName: 'Oakland High School', city: 'Murfreesboro', state: 'TN', mascot: 'Patriots' },
  { schoolName: 'Maryville High School', city: 'Maryville', state: 'TN', mascot: 'Rebels' },
  { schoolName: 'Alcoa High School', city: 'Alcoa', state: 'TN', mascot: 'Tornadoes' },
  { schoolName: 'Trinity High School', city: 'Louisville', state: 'KY', mascot: 'Shamrocks' },
  { schoolName: 'St. Xavier High School', city: 'Louisville', state: 'KY', mascot: 'Tigers' },
  { schoolName: 'Male High School', city: 'Louisville', state: 'KY', mascot: 'Bulldogs' },
  { schoolName: 'Frederick Douglass High School', city: 'Lexington', state: 'KY', mascot: 'Broncos' },
  { schoolName: 'Center Grove High School', city: 'Greenwood', state: 'IN', mascot: 'Trojans' },
  { schoolName: 'Ben Davis High School', city: 'Indianapolis', state: 'IN', mascot: 'Giants' },
  { schoolName: 'Warren Central High School', city: 'Indianapolis', state: 'IN', mascot: 'Warriors' },
  { schoolName: 'Cathedral High School', city: 'Indianapolis', state: 'IN', mascot: 'Irish' },
  { schoolName: 'Loyola Academy', city: 'Wilmette', state: 'IL', mascot: 'Ramblers' },
  { schoolName: 'Mount Carmel High School', city: 'Chicago', state: 'IL', mascot: 'Caravan' },
  { schoolName: 'East St. Louis High School', city: 'East St. Louis', state: 'IL', mascot: 'Flyers' },
  { schoolName: 'Lincoln-Way East High School', city: 'Frankfort', state: 'IL', mascot: 'Griffins' },
  { schoolName: 'Christian Brothers College High School', city: 'St. Louis', state: 'MO', mascot: 'Cadets' },
  { schoolName: 'De Smet Jesuit High School', city: 'St. Louis', state: 'MO', mascot: 'Spartans' },
  { schoolName: "Lee's Summit North High School", city: "Lee's Summit", state: 'MO', mascot: 'Broncos' },
  { schoolName: 'Liberty North High School', city: 'Liberty', state: 'MO', mascot: 'Eagles' },
  { schoolName: 'Bishop Miege High School', city: 'Roeland Park', state: 'KS', mascot: 'Stags' },
  { schoolName: 'Derby High School', city: 'Derby', state: 'KS', mascot: 'Panthers' },
  { schoolName: 'Mill Valley High School', city: 'Shawnee', state: 'KS', mascot: 'Jaguars' },
  { schoolName: 'Blue Valley Northwest High School', city: 'Overland Park', state: 'KS', mascot: 'Huskies' },
  { schoolName: 'Bixby High School', city: 'Bixby', state: 'OK', mascot: 'Spartans' },
  { schoolName: 'Jenks High School', city: 'Jenks', state: 'OK', mascot: 'Trojans' },
  { schoolName: 'Union High School', city: 'Tulsa', state: 'OK', mascot: 'Redhawks' },
  { schoolName: 'Owasso High School', city: 'Owasso', state: 'OK', mascot: 'Rams' },
  { schoolName: 'Bentonville High School', city: 'Bentonville', state: 'AR', mascot: 'Tigers' },
  { schoolName: 'Bryant High School', city: 'Bryant', state: 'AR', mascot: 'Hornets' },
  { schoolName: 'North Little Rock High School', city: 'North Little Rock', state: 'AR', mascot: 'Charging Wildcats' },
  { schoolName: 'Pulaski Academy', city: 'Little Rock', state: 'AR', mascot: 'Bruins' },
  { schoolName: 'Cherry Creek High School', city: 'Greenwood Village', state: 'CO', mascot: 'Bruins' },
  { schoolName: 'Valor Christian High School', city: 'Highlands Ranch', state: 'CO', mascot: 'Eagles' },
  { schoolName: 'Broomfield High School', city: 'Broomfield', state: 'CO', mascot: 'Eagles' },
  { schoolName: 'Columbine High School', city: 'Littleton', state: 'CO', mascot: 'Rebels' },
  { schoolName: 'Bishop Gorman High School', city: 'Las Vegas', state: 'NV', mascot: 'Gaels' },
  { schoolName: 'Liberty High School', city: 'Henderson', state: 'NV', mascot: 'Patriots' },
  { schoolName: 'Bingham High School', city: 'South Jordan', state: 'UT', mascot: 'Miners' },
  { schoolName: 'Corner Canyon High School', city: 'Draper', state: 'UT', mascot: 'Chargers' },
  { schoolName: 'Lone Peak High School', city: 'Highland', state: 'UT', mascot: 'Knights' },
  { schoolName: 'Timpview High School', city: 'Provo', state: 'UT', mascot: 'Thunderbirds' },
  { schoolName: 'Chandler High School', city: 'Chandler', state: 'AZ', mascot: 'Wolves' },
  { schoolName: 'Saguaro High School', city: 'Scottsdale', state: 'AZ', mascot: 'Sabercats' },
  { schoolName: 'Hamilton High School', city: 'Chandler', state: 'AZ', mascot: 'Huskies' },
  { schoolName: 'Basha High School', city: 'Chandler', state: 'AZ', mascot: 'Bears' },
  { schoolName: 'Centennial High School', city: 'Peoria', state: 'AZ', mascot: 'Coyotes' },
  { schoolName: 'La Cueva High School', city: 'Albuquerque', state: 'NM', mascot: 'Bears' },
  { schoolName: 'Cleveland High School', city: 'Rio Rancho', state: 'NM', mascot: 'Storm' },
  { schoolName: 'Rigby High School', city: 'Rigby', state: 'ID', mascot: 'Trojans' },
  { schoolName: 'Bishop Kelly High School', city: 'Boise', state: 'ID', mascot: 'Knights' },
  { schoolName: 'Bellevue High School', city: 'Bellevue', state: 'WA', mascot: 'Wolverines' },
  { schoolName: 'Eastside Catholic School', city: 'Sammamish', state: 'WA', mascot: 'Crusaders' },
  { schoolName: "O'Dea High School", city: 'Seattle', state: 'WA', mascot: 'Fighting Irish' },
  { schoolName: 'Lake Stevens High School', city: 'Lake Stevens', state: 'WA', mascot: 'Vikings' },
  { schoolName: 'Central Catholic High School', city: 'Portland', state: 'OR', mascot: 'Rams' },
  { schoolName: 'West Linn High School', city: 'West Linn', state: 'OR', mascot: 'Lions' },
  { schoolName: 'Sheldon High School', city: 'Eugene', state: 'OR', mascot: 'Irish' },
  { schoolName: 'Jesuit High School', city: 'Portland', state: 'OR', mascot: 'Crusaders' },
  { schoolName: 'Kahuku High School', city: 'Kahuku', state: 'HI', mascot: 'Red Raiders' },
  { schoolName: 'St. Louis School', city: 'Honolulu', state: 'HI', mascot: 'Crusaders' },
  { schoolName: 'Mililani High School', city: 'Mililani', state: 'HI', mascot: 'Trojans' },
  { schoolName: 'East High School', city: 'Anchorage', state: 'AK', mascot: 'Thunderbirds' },
  { schoolName: 'Service High School', city: 'Anchorage', state: 'AK', mascot: 'Cougars' },
  { schoolName: 'West Fargo High School', city: 'West Fargo', state: 'ND', mascot: 'Packers' },
  { schoolName: 'Bismarck High School', city: 'Bismarck', state: 'ND', mascot: 'Demons' },
  { schoolName: 'Sioux Falls Lincoln High School', city: 'Sioux Falls', state: 'SD', mascot: 'Patriots' },
  { schoolName: 'Brandon Valley High School', city: 'Brandon', state: 'SD', mascot: 'Lynx' },
  { schoolName: 'Omaha Westside High School', city: 'Omaha', state: 'NE', mascot: 'Warriors' },
  { schoolName: 'Millard South High School', city: 'Omaha', state: 'NE', mascot: 'Patriots' },
  { schoolName: 'Dowling Catholic High School', city: 'West Des Moines', state: 'IA', mascot: 'Maroons' },
  { schoolName: 'Ankeny High School', city: 'Ankeny', state: 'IA', mascot: 'Hawks' },
  { schoolName: 'Kimberly High School', city: 'Kimberly', state: 'WI', mascot: 'Papermakers' },
  { schoolName: 'Muskego High School', city: 'Muskego', state: 'WI', mascot: 'Warriors' },
  { schoolName: 'Eden Prairie High School', city: 'Eden Prairie', state: 'MN', mascot: 'Eagles' },
  { schoolName: 'Lakeville South High School', city: 'Lakeville', state: 'MN', mascot: 'Cougars' },
  { schoolName: 'King Philip Regional High School', city: 'Wrentham', state: 'MA', mascot: 'Warriors' },
  { schoolName: 'Everett High School', city: 'Everett', state: 'MA', mascot: 'Crimson Tide' },
  { schoolName: 'Catholic Memorial School', city: 'West Roxbury', state: 'MA', mascot: 'Knights' }
];
